# Generated by Django 5.1.5 on 2026-05-23 01:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Documento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("proposta", "Proposta"),
                            ("relatorio", "Relatório"),
                            ("ata", "Ata de Reunião"),
                            ("manual", "Manual"),
                            ("politica", "Política"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("em_revisao", "Em Revisão"),
                            ("aprovado", "Aprovado"),
                            ("arquivado", "Arquivado"),
                        ],
                        default="rascunho",
                        max_length=15,
                    ),
                ),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos/%Y/%m/"
                    ),
                ),
                ("url_externa", models.URLField(blank=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documentos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento",
                "verbose_name_plural": "Documentos",
                "db_table": "documentos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="VersaoDocumento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("numero_versao", models.PositiveIntegerField(default=1)),
                (
                    "arquivo",
                    models.FileField(
                        blank=True, null=True, upload_to="documentos/versoes/%Y/%m/"
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="versoes_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes",
                        to="documentos.documento",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versoes_documentos",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Versão do Documento",
                "verbose_name_plural": "Versões dos Documentos",
                "db_table": "documentos_versoes",
                "ordering": ["-numero_versao"],
            },
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(fields=["empresa", "tipo"], name="doc_emp_tipo_idx"),
        ),
        migrations.AddIndex(
            model_name="documento",
            index=models.Index(fields=["empresa", "status"], name="doc_emp_status_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="versaodocumento",
            unique_together={("documento", "numero_versao")},
        ),
    ]
