# Generated by Django 5.1.5 on 2026-05-21 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planejamento", "Planejamento"),
                            ("em_andamento", "Em Andamento"),
                            ("pausado", "Pausado"),
                            ("concluido", "Concluído"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planejamento",
                        max_length=15,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("data_inicio", models.DateField(blank=True, null=True)),
                ("data_prazo", models.DateField(blank=True, null=True)),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                ("cor", models.CharField(default="#6D28D9", max_length=7)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Projeto",
                "verbose_name_plural": "Projetos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Tarefa",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("a_fazer", "A Fazer"),
                            ("em_andamento", "Em Andamento"),
                            ("revisao", "Revisão"),
                            ("concluido", "Concluído"),
                        ],
                        default="a_fazer",
                        max_length=15,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("data_prazo", models.DateField(blank=True, null=True)),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                ("ordem", models.IntegerField(default=0)),
                (
                    "estimativa_horas",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "horas_gastas",
                    models.DecimalField(decimal_places=1, default=0, max_digits=5),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas_projetos",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas",
                        to="synapse_projetos.projeto",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas_responsavel",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa",
                "verbose_name_plural": "Tarefas",
                "ordering": ["ordem", "criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Comentario",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("texto", models.TextField()),
                ("editado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_tarefas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios_projetos",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "tarefa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comentarios",
                        to="synapse_projetos.tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comentário",
                "verbose_name_plural": "Comentários",
                "ordering": ["criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ChecklistItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                ("concluido", models.BooleanField(default=False)),
                ("ordem", models.IntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "tarefa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist",
                        to="synapse_projetos.tarefa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Checklist",
                "verbose_name_plural": "Itens de Checklist",
                "ordering": ["ordem", "criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(
                fields=["empresa", "status"], name="proj_emp_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(
                fields=["empresa", "prioridade"], name="proj_emp_prio_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(
                fields=["empresa", "responsavel"], name="proj_emp_resp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projeto",
            index=models.Index(
                fields=["empresa", "criado_em"], name="proj_emp_criado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(
                fields=["projeto", "status"], name="tar_proj_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(fields=["projeto", "ordem"], name="tar_proj_ordem_idx"),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(
                fields=["empresa", "responsavel"], name="tar_emp_resp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(
                fields=["empresa", "data_prazo"], name="tar_emp_prazo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefa",
            index=models.Index(fields=["empresa", "status"], name="tar_emp_status_idx"),
        ),
        migrations.AddIndex(
            model_name="comentario",
            index=models.Index(
                fields=["tarefa", "criado_em"], name="com_tar_criado_idx"
            ),
        ),
    ]
