# Generated by Django 5.1.5 on 2026-07-29 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipe", "0002_colunakanbanequipe_tarefapessoal_and_more"),
        ("synapse_projetos", "0001_initial_projetos"),
    ]

    operations = [
        migrations.AddField(
            model_name="tarefa",
            name="coluna_kanban_equipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tarefas_projeto",
                to="equipe.colunakanbanequipe",
            ),
        ),
    ]
