# Generated by Django 5.1.5 on 2026-05-23 20:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConteudoGerado",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("legenda_instagram", "Legenda para Instagram"),
                            ("titulo_produto", "Título de Produto"),
                            ("descricao_produto", "Descrição de Produto"),
                            ("hashtags", "Hashtags"),
                            ("ideia_pauta", "Ideia de Pauta"),
                            ("email_marketing", "E-mail Marketing"),
                            ("relatorio_negocio", "Relatório do Negócio"),
                            ("insight", "Insight"),
                            ("outro", "Outro"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "prompt_usuario",
                    models.TextField(help_text="O que o usuário pediu (simplificado)."),
                ),
                (
                    "prompt_completo",
                    models.TextField(
                        help_text="Prompt completo montado pelo sistema com contexto."
                    ),
                ),
                ("resultado", models.TextField(help_text="Resposta gerada pela IA.")),
                ("modelo_usado", models.CharField(max_length=100)),
                ("tokens_usados", models.IntegerField(default=0)),
                ("favorito", models.BooleanField(default=False)),
                ("copiado", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conteudos_ia_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteudos_ia",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo Gerado",
                "verbose_name_plural": "Conteúdos Gerados",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "tipo"],
                        name="ai_hub_cont_empresa_1e3470_idx",
                    ),
                    models.Index(
                        fields=["empresa", "criado_em"],
                        name="ai_hub_cont_empresa_5ae8f9_idx",
                    ),
                    models.Index(
                        fields=["empresa", "favorito"],
                        name="ai_hub_cont_empresa_747f87_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True, help_text="ID da task Celery.", max_length=255
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("conteudo", "Conteúdo"),
                            ("insight", "Insight"),
                            ("relatorio", "Relatório"),
                            ("analise", "Análise"),
                        ],
                        default="conteudo",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("processando", "Processando"),
                            ("concluido", "Concluído"),
                            ("erro", "Erro"),
                        ],
                        default="pendente",
                        max_length=20,
                    ),
                ),
                (
                    "parametros",
                    models.JSONField(
                        default=dict,
                        help_text="Parâmetros de entrada da task (tipo de conteúdo, campos, etc.).",
                    ),
                ),
                (
                    "resultado",
                    models.TextField(blank=True, help_text="Output quando concluído."),
                ),
                (
                    "erro",
                    models.TextField(
                        blank=True, help_text="Mensagem de erro se falhou."
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("concluido_em", models.DateTimeField(blank=True, null=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_ia",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task IA",
                "verbose_name_plural": "Tasks IA",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "status"],
                        name="ai_hub_task_empresa_57bfc6_idx",
                    ),
                    models.Index(
                        fields=["empresa", "criado_em"],
                        name="ai_hub_task_empresa_e1ea9f_idx",
                    ),
                ],
            },
        ),
    ]
