# Generated by Django 5.1.5 on 2026-07-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_hub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("conteudo", "Conteúdo"),
                    ("insight", "Insight"),
                    ("relatorio", "Relatório"),
                    ("analise", "Análise"),
                    ("chat", "Chat"),
                ],
                default="conteudo",
                max_length=20,
            ),
        ),
    ]
