# Generated by Django 5.1.15 on 2026-05-15 18:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('synapse_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('pessoa_fisica', 'Pessoa Física'), ('pessoa_juridica', 'Pessoa Jurídica')], default='pessoa_fisica', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('documento', models.CharField(blank=True, max_length=20)),
                ('nome_empresa', models.CharField(blank=True, max_length=255)),
                ('endereco_cidade', models.CharField(blank=True, max_length=100)),
                ('endereco_estado', models.CharField(blank=True, max_length=2)),
                ('segmento', models.CharField(blank=True, max_length=100)),
                ('status_funil', models.CharField(choices=[('lead', 'Lead'), ('contato', 'Contato'), ('proposta', 'Proposta'), ('negociacao', 'Negociação'), ('fechado', 'Fechado'), ('perdido', 'Perdido')], default='lead', max_length=20)),
                ('origem', models.CharField(blank=True, choices=[('indicacao', 'Indicação'), ('instagram', 'Instagram'), ('google', 'Google'), ('whatsapp', 'WhatsApp'), ('site', 'Site'), ('outro', 'Outro')], max_length=20)),
                ('valor_total_compras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantidade_compras', models.IntegerField(default=0)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('proximo_followup', models.DateField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('notas', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='synapse_auth.empresa')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='InteracaoCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('ligacao', 'Ligação'), ('reuniao', 'Reunião'), ('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('visita', 'Visita'), ('venda', 'Venda'), ('proposta', 'Proposta'), ('outro', 'Outro')], max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('data_interacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('proximo_followup', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='synapse_clientes.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacoes_clientes', to='synapse_auth.empresa')),
            ],
            options={
                'verbose_name': 'Interação com Cliente',
                'verbose_name_plural': 'Interações com Clientes',
                'ordering': ['-data_interacao'],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'status_funil'], name='synapse_cli_empresa_fbbb21_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'ativo'], name='synapse_cli_empresa_1f6e76_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'criado_em'], name='synapse_cli_empresa_0faa92_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'proximo_followup'], name='synapse_cli_empresa_f8fff4_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'ultima_compra'], name='synapse_cli_empresa_cf901b_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaocliente',
            index=models.Index(fields=['cliente', 'criado_em'], name='synapse_cli_cliente_81e91f_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaocliente',
            index=models.Index(fields=['empresa', 'tipo'], name='synapse_cli_empresa_43810e_idx'),
        ),
        migrations.AddIndex(
            model_name='interacaocliente',
            index=models.Index(fields=['empresa', 'proximo_followup'], name='synapse_cli_empresa_9d8f01_idx'),
        ),
    ]
