# Generated by Django 5.1.5 on 2026-07-22 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_clientes", "0001_initial"),
        ("synapse_estoque", "0002_add_preco_desconto_movimentacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="interacaocliente",
            name="movimentacao_estoque",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interacao_origem",
                to="synapse_estoque.movimentacao",
            ),
        ),
    ]
