# Generated by Django 5.1.5 on 2026-07-23 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_clientes", "0002_interacaocliente_movimentacao_estoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="interacaocliente",
            name="data_prevista_pagamento",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="interacaocliente",
            name="notificacao_enviada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="interacaocliente",
            name="status_pagamento",
            field=models.CharField(
                choices=[
                    ("pago", "Pago"),
                    ("pendente", "Pendente"),
                    ("cancelado", "Cancelado"),
                    ("nao_se_aplica", "Não se aplica"),
                ],
                default="nao_se_aplica",
                max_length=20,
            ),
        ),
    ]
