# Generated by Django 5.1.5 on 2026-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_clientes", "0003_interacaocliente_data_prevista_pagamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="valor_a_receber",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="cliente",
            name="valor_recebido",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
