# Generated by Django 5.1.5 on 2026-07-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_clientes", "0004_cliente_valor_a_receber_cliente_valor_recebido"),
        ("synapse_financeiro", "0003_lancamento_data_quitacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interacaocliente",
            name="lancamento_financeiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interacao_origem",
                to="synapse_financeiro.lancamento",
            ),
        ),
    ]
