# Generated by Django 5.2.17 on 2026-08-27 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_clientes", "0005_interacaocliente_lancamento_financeiro"),
        ("synapse_vendas", "0002_itemvenda_descricao_alter_itemvenda_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="interacaocliente",
            name="migrada_para_venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="interacao_migrada",
                to="synapse_vendas.venda",
            ),
        ),
    ]
