# Generated by Django 5.1.5 on 2026-07-08 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0003_customuser_is_staff_synapse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogAlteracaoPlano",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("plano_anterior", models.CharField(max_length=20)),
                ("plano_novo", models.CharField(max_length=20)),
                ("observacao", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("sucesso", "Sucesso"), ("erro", "Erro")],
                        default="sucesso",
                        max_length=10,
                    ),
                ),
                ("erro", models.TextField(blank=True, default="")),
                ("alterado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "alterado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alteracoes_plano_feitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_alteracao_plano",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Alteração de Plano",
                "verbose_name_plural": "Logs de Alteração de Plano",
                "db_table": "synapse_log_alteracao_plano",
                "ordering": ["-alterado_em"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "-alterado_em"],
                        name="synapse_log_empresa_e631eb_idx",
                    )
                ],
            },
        ),
    ]
