# Generated by Django 5.1.5 on 2026-07-28 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_painel_admin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logalteracaoplano",
            name="acao",
            field=models.CharField(
                choices=[
                    ("troca_plano", "Troca de plano"),
                    ("criacao", "Criação da empresa"),
                    ("suspenso", "Suspensa"),
                    ("reativado", "Reativada"),
                ],
                default="troca_plano",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("empresa_id", models.UUIDField(db_index=True)),
                ("empresa_nome", models.CharField(max_length=255)),
                (
                    "acao",
                    models.CharField(
                        choices=[
                            ("empresa_excluida", "Empresa excluída definitivamente")
                        ],
                        default="empresa_excluida",
                        max_length=32,
                    ),
                ),
                (
                    "realizado_por_email",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("detalhes", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "realizado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditorias_realizadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Auditoria",
                "verbose_name_plural": "Logs de Auditoria",
                "db_table": "synapse_audit_log",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["empresa_id", "-criado_em"],
                        name="synapse_aud_empresa_8ecc77_idx",
                    )
                ],
            },
        ),
    ]
