# Generated by Django 5.1.5 on 2026-08-06 20:11

import uuid
from django.db import migrations, models


PLANOS_COMERCIAIS = ["starter", "pro", "business"]


def seed_planos(apps, schema_editor):
    """
    Cria a linha dos 3 planos comerciais com preço e limites em branco.
    Nada é inventado aqui: a landing mostra "a definir" até o staff preencher.
    """
    ConfiguracaoPlano = apps.get_model("synapse_painel_admin", "ConfiguracaoPlano")
    for plano in PLANOS_COMERCIAIS:
        ConfiguracaoPlano.objects.get_or_create(plano=plano)


def remove_planos(apps, schema_editor):
    ConfiguracaoPlano = apps.get_model("synapse_painel_admin", "ConfiguracaoPlano")
    ConfiguracaoPlano.objects.filter(plano__in=PLANOS_COMERCIAIS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_painel_admin", "0002_logalteracaoplano_acao_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfiguracaoPlano",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plano",
                    models.CharField(
                        choices=[
                            ("starter", "Starter"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "preco_mensal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "preco_anual",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("limite_usuarios", models.IntegerField(blank=True, null=True)),
                ("limite_armazenamento_gb", models.IntegerField(blank=True, null=True)),
                (
                    "descricao_suporte",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Configuração de Plano",
                "verbose_name_plural": "Configurações de Plano",
                "db_table": "synapse_configuracao_plano",
                "ordering": ["plano"],
            },
        ),
        migrations.RunPython(seed_planos, remove_planos),
    ]
