# Generated by Django 5.1.5 on 2026-05-23 01:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notificacao",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("financeiro", "Financeiro"),
                            ("estoque", "Estoque"),
                            ("cliente", "Cliente"),
                            ("fornecedor", "Fornecedor"),
                            ("projeto", "Projeto"),
                            ("equipe", "Equipe"),
                            ("documento", "Documento"),
                            ("sistema", "Sistema"),
                        ],
                        default="sistema",
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("mensagem", models.TextField()),
                ("lida", models.BooleanField(default=False)),
                ("data_leitura", models.DateTimeField(blank=True, null=True)),
                (
                    "acao_url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="URL para onde o usuário deve navegar ao clicar",
                        max_length=500,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("alta", "Alta"),
                            ("urgente", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        help_text="Usuário que recebe a notificação",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "db_table": "notificacoes",
                "ordering": ["-criado_em"],
                "indexes": [
                    models.Index(
                        fields=["usuario", "lida"], name="notif_usuario_lida_idx"
                    ),
                    models.Index(
                        fields=["usuario", "criado_em"], name="notif_usuario_criado_idx"
                    ),
                    models.Index(
                        fields=["empresa", "criado_em"], name="notif_empresa_criado_idx"
                    ),
                    models.Index(
                        fields=["usuario", "tipo"], name="notif_usuario_tipo_idx"
                    ),
                ],
            },
        ),
    ]
