# Generated by Django 5.2.17 on 2026-09-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificacoes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificacao",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("financeiro", "Financeiro"),
                    ("estoque", "Estoque"),
                    ("cliente", "Cliente"),
                    ("fornecedor", "Fornecedor"),
                    ("projeto", "Projeto"),
                    ("agenda", "Agenda"),
                    ("equipe", "Equipe"),
                    ("documento", "Documento"),
                    ("sistema", "Sistema"),
                ],
                default="sistema",
                max_length=20,
            ),
        ),
    ]
