# Generated by Django 5.1.5 on 2026-05-23 01:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MembroEquipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cargo", models.CharField(blank=True, max_length=100)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("bio", models.TextField(blank=True)),
                ("data_entrada", models.DateField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros_equipe",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membros_equipe",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Equipe",
                "verbose_name_plural": "Membros da Equipe",
                "db_table": "equipe_membros",
            },
        ),
        migrations.CreateModel(
            name="MetaMembro",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("vendas", "Vendas"),
                            ("tarefas", "Tarefas"),
                            ("clientes", "Clientes"),
                            ("projetos", "Projetos"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=20,
                    ),
                ),
                (
                    "valor_meta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "valor_atual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("semanal", "Semanal"),
                            ("mensal", "Mensal"),
                            ("trimestral", "Trimestral"),
                            ("anual", "Anual"),
                        ],
                        default="mensal",
                        max_length=15,
                    ),
                ),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("atingida", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas_equipe",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metas",
                        to="equipe.membroequipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Meta do Membro",
                "verbose_name_plural": "Metas dos Membros",
                "db_table": "equipe_metas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="membroequipe",
            index=models.Index(
                fields=["empresa", "ativo"], name="equipe_emp_ativo_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membroequipe",
            index=models.Index(
                fields=["usuario", "ativo"], name="equipe_usr_ativo_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membroequipe",
            unique_together={("empresa", "usuario")},
        ),
    ]
