# Generated by Django 5.1.5 on 2026-07-29 03:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipe", "0001_initial"),
        (
            "synapse_auth",
            "0005_empresa_data_suspensao_empresa_motivo_suspensao_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ColunaKanbanEquipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ordem", models.IntegerField(default=0)),
                ("cor", models.CharField(blank=True, default="", max_length=9)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="colunas_kanban_equipe",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coluna do Kanban da Equipe",
                "verbose_name_plural": "Colunas do Kanban da Equipe",
                "db_table": "equipe_kanban_colunas",
                "ordering": ["ordem", "criado_em"],
            },
        ),
        migrations.CreateModel(
            name="TarefaPessoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, default="")),
                ("prazo", models.DateField(blank=True, null=True)),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                ("ordem", models.IntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "coluna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas_pessoais",
                        to="equipe.colunakanbanequipe",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tarefas_pessoais_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas_pessoais",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarefas_pessoais",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarefa Pessoal",
                "verbose_name_plural": "Tarefas Pessoais",
                "db_table": "equipe_tarefas_pessoais",
                "ordering": ["ordem", "criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="colunakanbanequipe",
            index=models.Index(
                fields=["empresa", "ordem"], name="equipe_col_ordem_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefapessoal",
            index=models.Index(
                fields=["empresa", "responsavel"], name="equipe_tp_resp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tarefapessoal",
            index=models.Index(
                fields=["coluna", "ordem"], name="equipe_tp_col_ordem_idx"
            ),
        ),
    ]
