# Generated by Django 5.1.5 on 2026-07-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipe", "0003_seed_colunas_kanban"),
    ]

    operations = [
        migrations.AddField(
            model_name="metamembro",
            name="email_conclusao_enviado",
            field=models.BooleanField(default=False),
        ),
    ]
