# Generated by Django 5.1.5 on 2026-07-04 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0002_alter_passwordresettoken_options_and_more"),
        ("synapse_clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                ("descricao", models.TextField(blank=True, default="")),
                ("data_inicio", models.DateTimeField()),
                ("data_fim", models.DateTimeField()),
                ("dia_inteiro", models.BooleanField(default=False)),
                ("local", models.CharField(blank=True, default="", max_length=255)),
                ("cor", models.CharField(default="#6D28D9", max_length=7)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_agenda",
                        to="synapse_clientes.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="eventos_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eventos_agenda",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["data_inicio"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "data_inicio"],
                        name="synapse_age_empresa_c7b40b_idx",
                    ),
                    models.Index(
                        fields=["empresa", "data_fim"],
                        name="synapse_age_empresa_ff9640_idx",
                    ),
                ],
            },
        ),
    ]
