# Generated by Django 5.2.17 on 2026-09-12 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_agenda", "0001_initial"),
        ("synapse_auth", "0009_customuser_tema_modo"),
        ("synapse_clientes", "0006_interacaocliente_migrada_para_venda"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="lembrete_antecedencia",
            field=models.PositiveIntegerField(
                choices=[
                    (0, "Sem lembrete"),
                    (10, "10 minutos antes"),
                    (30, "30 minutos antes"),
                    (60, "1 hora antes"),
                    (1440, "1 dia antes"),
                ],
                default=0,
                help_text="Minutos antes do início para avisar. 0 = sem lembrete.",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="lembrete_enviado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="evento",
            index=models.Index(
                fields=["lembrete_enviado", "data_inicio"],
                name="synapse_age_lembret_bf303c_idx",
            ),
        ),
    ]
