# Generated by Django 5.2.17 on 2026-09-26 17:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_agenda", "0003_normaliza_dia_inteiro"),
        ("synapse_auth", "0011_empresa_duracao_padrao_agenda"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaEvento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=60)),
                ("cor", models.CharField(default="#6D28D9", max_length=7)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem", models.PositiveSmallIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categorias_evento",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria de evento",
                "verbose_name_plural": "Categorias de evento",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.AddField(
            model_name="evento",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos",
                to="synapse_agenda.categoriaevento",
            ),
        ),
        migrations.AddIndex(
            model_name="categoriaevento",
            index=models.Index(
                fields=["empresa", "ativo"], name="synapse_age_empresa_1e2cef_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriaevento",
            constraint=models.UniqueConstraint(
                fields=("empresa", "nome"),
                name="categoria_evento_nome_unico_por_empresa",
            ),
        ),
    ]
