# Generated by Django 5.2.17 on 2026-09-28 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_agenda", "0004_categoria_evento"),
        ("synapse_projetos", "0002_tarefa_coluna_kanban_equipe"),
        ("synapse_vendas", "0005_fiado_nao_cobra_retroativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="evento",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_agenda",
                to="synapse_projetos.projeto",
            ),
        ),
        migrations.AddField(
            model_name="evento",
            name="venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="eventos_agenda",
                to="synapse_vendas.venda",
            ),
        ),
    ]
