# Generated by Django 5.1.15 on 2026-05-15 20:31

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('synapse_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaFornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('cor', models.CharField(default='#6D28D9', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_fornecedor', to='synapse_auth.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Fornecedor',
                'verbose_name_plural': 'Categorias de Fornecedor',
                'db_table': 'synapse_categorias_fornecedor',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('nome_contato', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('site', models.URLField(blank=True)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('endereco_cidade', models.CharField(blank=True, max_length=100)),
                ('endereco_estado', models.CharField(blank=True, max_length=2)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('negociando', 'Negociando'), ('suspenso', 'Suspenso'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('condicoes_pagamento', models.CharField(blank=True, max_length=255)),
                ('prazo_entrega_dias', models.IntegerField(blank=True, null=True)),
                ('valor_total_compras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantidade_pedidos', models.IntegerField(default=0)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('avaliacao_qualidade', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avaliacao_prazo', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avaliacao_preco', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('score_synapse', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('notas', models.TextField(blank=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores', to='synapse_fornecedores.categoriafornecedor')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fornecedores_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='synapse_auth.empresa')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'db_table': 'synapse_fornecedores',
                'ordering': ['-score_synapse', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='CompraFornecedor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data_compra', models.DateField()),
                ('numero_nf', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_fornecedor_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_fornecedor', to='synapse_auth.empresa')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='synapse_fornecedores.fornecedor')),
            ],
            options={
                'verbose_name': 'Compra de Fornecedor',
                'verbose_name_plural': 'Compras de Fornecedores',
                'db_table': 'synapse_compras_fornecedor',
                'ordering': ['-data_compra'],
            },
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['empresa', 'status'], name='forn_empresa_status_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['empresa', 'categoria'], name='forn_empresa_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['empresa', 'score_synapse'], name='forn_empresa_score_idx'),
        ),
        migrations.AddIndex(
            model_name='fornecedor',
            index=models.Index(fields=['empresa', 'criado_em'], name='forn_empresa_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='comprafornecedor',
            index=models.Index(fields=['fornecedor', 'criado_em'], name='compra_forn_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='comprafornecedor',
            index=models.Index(fields=['empresa', 'criado_em'], name='compra_emp_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='comprafornecedor',
            index=models.Index(fields=['empresa', 'status'], name='compra_emp_status_idx'),
        ),
    ]
