# Generated by Django 5.1.5 on 2026-07-24 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_financeiro", "0003_lancamento_data_quitacao_and_more"),
        ("synapse_fornecedores", "0002_comprafornecedor_movimentacao_estoque"),
    ]

    operations = [
        migrations.AddField(
            model_name="comprafornecedor",
            name="lancamento_financeiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="compra_origem",
                to="synapse_financeiro.lancamento",
            ),
        ),
    ]
