# Generated by Django 5.2.17 on 2026-08-26 13:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0009_customuser_tema_modo"),
        ("synapse_clientes", "0005_interacaocliente_lancamento_financeiro"),
        ("synapse_estoque", "0002_add_preco_desconto_movimentacao"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "data_venda",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "desconto",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "forma_pagamento",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dinheiro", "Dinheiro"),
                            ("pix", "PIX"),
                            ("cartao", "Cartão"),
                            ("outro", "Outro"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "status_pagamento",
                    models.CharField(
                        choices=[("pago", "Pago"), ("pendente", "Pendente")],
                        default="pago",
                        max_length=20,
                    ),
                ),
                ("data_prevista_pagamento", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, default="")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendas",
                        to="synapse_clientes.cliente",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vendas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vendas",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venda",
                "verbose_name_plural": "Vendas",
                "db_table": "vendas",
                "ordering": ["-data_venda", "-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="ItemVenda",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens_venda",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="itens_venda",
                        to="synapse_estoque.produto",
                    ),
                ),
                (
                    "venda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="synapse_vendas.venda",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da venda",
                "verbose_name_plural": "Itens da venda",
                "db_table": "venda_itens",
                "ordering": ["criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["empresa", "-data_venda"], name="venda_empresa_data_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="venda",
            index=models.Index(
                fields=["empresa", "status_pagamento"], name="venda_empresa_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemvenda",
            index=models.Index(
                fields=["empresa", "produto"], name="itemvenda_emp_prod_idx"
            ),
        ),
    ]
