# Generated by Django 5.2.17 on 2026-08-27 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_estoque", "0002_add_preco_desconto_movimentacao"),
        ("synapse_vendas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemvenda",
            name="descricao",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="itemvenda",
            name="produto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="itens_venda",
                to="synapse_estoque.produto",
            ),
        ),
    ]
