# Generated by Django 5.2.17 on 2026-08-27 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_financeiro", "0003_lancamento_data_quitacao_and_more"),
        ("synapse_vendas", "0002_itemvenda_descricao_alter_itemvenda_produto"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="lancamento_financeiro",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="venda_origem",
                to="synapse_financeiro.lancamento",
            ),
        ),
    ]
