# Generated by Django 5.2.17 on 2026-09-03 00:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_vendas", "0003_venda_lancamento_financeiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="devedor",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="venda",
            name="notificacao_enviada",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="venda",
            name="valor_recebido",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="venda",
            name="status_pagamento",
            field=models.CharField(
                choices=[
                    ("pago", "Pago"),
                    ("pendente", "Pendente"),
                    ("cancelado", "Cancelado"),
                ],
                default="pago",
                max_length=20,
            ),
        ),
    ]
