# Generated by Django 5.1.5 on 2026-07-13 01:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0004_customuser_viu_aviso_recorrencias"),
        ("synapse_financeiro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recorrencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("titulo", models.CharField(max_length=255)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("receita", "Receita"), ("despesa", "Despesa")],
                        max_length=10,
                    ),
                ),
                ("valor_padrao", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descricao", models.TextField(blank=True, default="")),
                ("ativa", models.BooleanField(default=True)),
                (
                    "frequencia_tipo",
                    models.CharField(
                        choices=[
                            ("mensal", "Mensal"),
                            ("semanal", "Semanal"),
                            ("diario", "Diário"),
                        ],
                        default="mensal",
                        max_length=10,
                    ),
                ),
                (
                    "dia_referencia",
                    models.IntegerField(
                        default=1,
                        help_text="Mensal: dia do mês (1-31). Semanal: dia da semana (0=seg..6=dom). Diário: ignorado.",
                    ),
                ),
                (
                    "usa_dia_util",
                    models.BooleanField(
                        default=False,
                        help_text="Se cair em fim de semana/feriado nacional, empurra pro próximo dia útil.",
                    ),
                ),
                (
                    "avisar_com_antecedencia",
                    models.IntegerField(
                        default=0,
                        help_text="Dias: 0 = no dia, 1 = 1 dia antes, -1 = 1 dia depois.",
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorrencias",
                        to="synapse_financeiro.categoria",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorrencias_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recorrencias",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recorrência",
                "verbose_name_plural": "Recorrências",
                "db_table": "synapse_recorrencias",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="OcorrenciaRecorrencia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data_esperada", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendente", "Pendente"),
                            ("confirmada", "Confirmada"),
                            ("adiada", "Adiada"),
                            ("cancelada", "Cancelada"),
                            ("encerrada", "Encerrada"),
                        ],
                        default="pendente",
                        max_length=12,
                    ),
                ),
                (
                    "valor_confirmado",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("data_confirmacao", models.DateField(blank=True, null=True)),
                ("data_adiada_para", models.DateField(blank=True, null=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "lancamento_gerado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ocorrencia_origem",
                        to="synapse_financeiro.lancamento",
                    ),
                ),
                (
                    "recorrencia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="synapse_recorrencias.recorrencia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ocorrência de Recorrência",
                "verbose_name_plural": "Ocorrências de Recorrência",
                "db_table": "synapse_ocorrencias_recorrencia",
                "ordering": ["-data_esperada", "-criada_em"],
            },
        ),
        migrations.AddIndex(
            model_name="recorrencia",
            index=models.Index(
                fields=["empresa", "ativa"], name="synapse_rec_empresa_8b41e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ocorrenciarecorrencia",
            index=models.Index(
                fields=["recorrencia", "status"], name="synapse_oco_recorre_48487b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ocorrenciarecorrencia",
            index=models.Index(
                fields=["status", "data_esperada"], name="synapse_oco_status_025ca9_idx"
            ),
        ),
    ]
