# Generated by Django 5.1.5 on 2026-07-15 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("synapse_auth", "0004_customuser_viu_aviso_recorrencias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Caixinha",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("cor", models.CharField(default="#6366f1", max_length=7)),
                ("icone", models.CharField(blank=True, max_length=10)),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "meta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="caixinhas_criadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caixinhas",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caixinha",
                "verbose_name_plural": "Caixinhas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="MovimentoCaixinha",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("deposito", "Depósito"), ("retirada", "Retirada")],
                        max_length=10,
                    ),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "caixinha",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos",
                        to="synapse_caixinhas.caixinha",
                    ),
                ),
                (
                    "criado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="movimentos_caixinhas_criados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimentos_caixinhas",
                        to="synapse_auth.empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimento de Caixinha",
                "verbose_name_plural": "Movimentos de Caixinhas",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.AddIndex(
            model_name="caixinha",
            index=models.Index(
                fields=["empresa", "criado_em"], name="cx_emp_criado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentocaixinha",
            index=models.Index(
                fields=["empresa", "criado_em"], name="cxmov_emp_criado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movimentocaixinha",
            index=models.Index(
                fields=["caixinha", "criado_em"], name="cxmov_cx_criado_idx"
            ),
        ),
    ]
