# Generated by Django 5.1.15 on 2026-05-14 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('synapse_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEstoque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('cor', models.CharField(default='#6D28D9', max_length=7, verbose_name='cor')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_estoque', to='synapse_auth.empresa')),
            ],
            options={
                'verbose_name': 'Categoria de Estoque',
                'verbose_name_plural': 'Categorias de Estoque',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('codigo_barras', models.CharField(blank=True, max_length=50, verbose_name='código de barras')),
                ('unidade', models.CharField(choices=[('unidade', 'Unidade'), ('kg', 'Quilograma'), ('litro', 'Litro'), ('metro', 'Metro'), ('caixa', 'Caixa'), ('pacote', 'Pacote')], default='unidade', max_length=20, verbose_name='unidade')),
                ('preco_custo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='preço de custo')),
                ('preco_venda', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='preço de venda')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='estoque atual')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='estoque mínimo')),
                ('estoque_maximo', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='estoque máximo')),
                ('imagem_url', models.CharField(blank=True, max_length=500, verbose_name='URL da imagem')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='synapse_estoque.categoriaestoque')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_criados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='synapse_auth.empresa')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('sku_variacao', models.CharField(blank=True, max_length=100, verbose_name='SKU da variação')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='estoque atual')),
                ('preco_venda', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço de venda')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='synapse_estoque.produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferência')], max_length=20, verbose_name='tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade')),
                ('estoque_antes', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='estoque antes')),
                ('estoque_depois', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='estoque depois')),
                ('motivo', models.CharField(choices=[('compra', 'Compra'), ('venda', 'Venda'), ('perda', 'Perda'), ('devolucao', 'Devolução'), ('inventario', 'Inventário'), ('ajuste_manual', 'Ajuste Manual'), ('transferencia', 'Transferência')], max_length=30, verbose_name='motivo')),
                ('referencia', models.CharField(blank=True, max_length=255, verbose_name='referência')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes_estoque', to='synapse_auth.empresa')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='synapse_estoque.produto')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes', to='synapse_estoque.variacao')),
            ],
            options={
                'verbose_name': 'Movimentação de Estoque',
                'verbose_name_plural': 'Movimentações de Estoque',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'ativo'], name='produto_empresa_ativo_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'categoria'], name='produto_empresa_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'criado_em'], name='produto_empresa_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['empresa', 'nome'], name='produto_empresa_nome_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variacao',
            unique_together={('produto', 'nome')},
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['empresa', 'criado_em'], name='mov_empresa_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['produto', 'criado_em'], name='mov_produto_criado_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['empresa', 'tipo'], name='mov_empresa_tipo_idx'),
        ),
    ]
