# Generated by Django 5.1.5 on 2026-05-30 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_estoque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="desconto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Percentual de desconto aplicado (0-100).",
                max_digits=5,
                verbose_name="desconto (%)",
            ),
        ),
        migrations.AddField(
            model_name="movimentacao",
            name="preco_unitario",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Preço unitário de venda (obrigatório para saídas do tipo venda).",
                max_digits=12,
                null=True,
                verbose_name="preço unitário",
            ),
        ),
    ]
