# Generated by Django 5.2.17 on 2026-08-30 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_estoque", "0002_add_preco_desconto_movimentacao"),
        ("synapse_vendas", "0003_venda_lancamento_financeiro"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimentacao",
            name="venda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="movimentacoes",
                to="synapse_vendas.venda",
            ),
        ),
    ]
