# Generated by Django 5.1.15 on 2026-05-14 02:34

import django.db.models.deletion
import modules.auth.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(blank=True, default='', max_length=18)),
                ('segmento', models.CharField(choices=[('varejo', 'Varejo'), ('servicos', 'Serviços'), ('alimentacao', 'Alimentação'), ('moda', 'Moda'), ('eventos', 'Eventos'), ('agencia', 'Agência'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('plano', models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('business', 'Business'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('plano_ativo', models.BooleanField(default=True)),
                ('plano_validade', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'synapse_empresas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('perfil', models.CharField(choices=[('admin', 'Administrador'), ('gerente', 'Gerente'), ('colaborador', 'Colaborador')], default='admin', max_length=20)),
                ('avatar_url', models.CharField(blank=True, default='', max_length=500)),
                ('ativo', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='synapse_auth.empresa')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'synapse_users',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('expira_em', models.DateTimeField(default=modules.auth.models._expira_em_default)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Redefinição de Senha',
                'verbose_name_plural': 'Tokens de Redefinição de Senha',
                'db_table': 'synapse_password_reset_tokens',
                'ordering': ['-criado_em'],
            },
        ),
    ]
