# Generated by Django 5.1.5 on 2026-07-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="passwordresettoken",
            options={
                "ordering": ["-criado_em"],
                "verbose_name": "Token de Definição de Senha",
                "verbose_name_plural": "Tokens de Definição de Senha",
            },
        ),
        migrations.AddField(
            model_name="passwordresettoken",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("reset", "Redefinição de senha"),
                    ("convite", "Convite / primeiro acesso"),
                ],
                db_index=True,
                default="reset",
                max_length=10,
            ),
        ),
    ]
