# Generated by Django 5.1.5 on 2026-07-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0002_alter_passwordresettoken_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_staff_synapse",
            field=models.BooleanField(default=False),
        ),
    ]
