# Generated by Django 5.1.5 on 2026-07-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0003_customuser_is_staff_synapse"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="viu_aviso_recorrencias",
            field=models.BooleanField(default=False),
        ),
    ]
