# Generated by Django 5.1.5 on 2026-07-28 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0004_customuser_viu_aviso_recorrencias"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="data_suspensao",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="motivo_suspensao",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="empresa",
            name="status",
            field=models.CharField(
                choices=[("ativa", "Ativa"), ("suspensa", "Suspensa")],
                db_index=True,
                default="ativa",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="suspensa_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empresas_suspensas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
