# Generated by Django 5.1.5 on 2026-08-05 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "synapse_auth",
            "0005_empresa_data_suspensao_empresa_motivo_suspensao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="modulo_agenda",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="modulo_documentos",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="modulo_equipe",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="modulo_estoque",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="modulo_fornecedores",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="empresa",
            name="modulo_projetos",
            field=models.BooleanField(default=True),
        ),
    ]
