# Generated by Django 5.1.5 on 2026-08-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "synapse_auth",
            "0006_empresa_modulo_agenda_empresa_modulo_documentos_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="tema_fonte",
            field=models.CharField(
                choices=[
                    ("padrao", "Padrão"),
                    ("serifada", "Serifada"),
                    ("geometrica", "Geométrica"),
                ],
                default="padrao",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="tema_paleta",
            field=models.CharField(
                choices=[
                    ("synapse", "Synapse"),
                    ("oceano", "Oceano"),
                    ("floresta", "Floresta"),
                    ("ambar", "Âmbar"),
                    ("grafite", "Grafite"),
                ],
                default="synapse",
                max_length=20,
            ),
        ),
    ]
