# Generated by Django 5.1.5 on 2026-08-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0007_empresa_tema_fonte_empresa_tema_paleta"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tamanho_fonte",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("medio", "Médio"),
                    ("grande", "Grande"),
                    ("maior", "Maior"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="empresa",
            name="tema_fonte",
            field=models.CharField(
                choices=[
                    ("padrao", "Padrão"),
                    ("serifada", "Serifada"),
                    ("geometrica", "Geométrica"),
                    ("plex", "IBM Plex Sans"),
                    ("figtree", "Figtree"),
                ],
                default="padrao",
                max_length=20,
            ),
        ),
    ]
