# Generated by Django 5.1.5 on 2026-08-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0008_customuser_tamanho_fonte_alter_empresa_tema_fonte"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tema_modo",
            field=models.CharField(
                choices=[
                    ("claro", "Claro"),
                    ("escuro", "Escuro"),
                    ("sistema", "Seguir o sistema"),
                ],
                default="sistema",
                max_length=10,
            ),
        ),
    ]
