# Generated by Django 5.2.17 on 2026-09-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0009_customuser_tema_modo"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="agenda_hora_fim",
            field=models.PositiveSmallIntegerField(
                default=20, help_text="Hora em que o expediente termina (1–24)."
            ),
        ),
        migrations.AddField(
            model_name="empresa",
            name="agenda_hora_inicio",
            field=models.PositiveSmallIntegerField(
                default=7, help_text="Hora em que o expediente começa (0–23)."
            ),
        ),
    ]
