# Generated by Django 5.2.17 on 2026-09-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0010_empresa_expediente_agenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="empresa",
            name="agenda_duracao_padrao",
            field=models.PositiveSmallIntegerField(
                default=60, help_text="Duração padrão de um evento novo, em minutos."
            ),
        ),
    ]
