# Generated by Django 5.1.5 on 2026-07-13 20:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_auth", "0004_customuser_viu_aviso_recorrencias"),
        ("synapse_financeiro", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogEdicaoLancamento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("editado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "acao",
                    models.CharField(
                        choices=[("editado", "Editado"), ("excluido", "Excluído")],
                        max_length=10,
                    ),
                ),
                ("motivo", models.TextField()),
                ("snapshot_antes", models.JSONField()),
                ("snapshot_depois", models.JSONField(blank=True, null=True)),
                (
                    "editado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="edicoes_lancamentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs_edicao_lancamentos",
                        to="synapse_auth.empresa",
                    ),
                ),
                (
                    "lancamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs_edicao",
                        to="synapse_financeiro.lancamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Edição de Lançamento",
                "verbose_name_plural": "Logs de Edição de Lançamentos",
                "ordering": ["-editado_em"],
                "indexes": [
                    models.Index(
                        fields=["empresa", "lancamento"], name="fin_log_emp_lanc_idx"
                    ),
                    models.Index(
                        fields=["empresa", "editado_em"], name="fin_log_emp_data_idx"
                    ),
                ],
            },
        ),
    ]
