# Generated by Django 5.1.5 on 2026-07-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("synapse_financeiro", "0002_logedicaolancamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="lancamento",
            name="data_quitacao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="data_retorno_esperado",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="direcao_emprestimo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("emprestei", "Eu emprestei"),
                    ("peguei_emprestado", "Peguei emprestado"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="emprestimo_perdoado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="emprestimo_quitado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lancamento",
            name="pessoa_emprestimo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lancamento",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("receita", "Receita"),
                    ("despesa", "Despesa"),
                    ("emprestimo", "Empréstimo"),
                ],
                max_length=10,
            ),
        ),
    ]
